[project]
name = "advenv"
version = "0.1.0"
dependencies = ["rich"]

[project.scripts]
hello = "helloworld:hello_world"

[build-system]
requires = ["hatchling"]
backend-path = ["src"]
build-backend = "mybuild"

[tool.hatch.build.targets.wheel]
include=["src/helloworld.py"]
